config/routes.rb
Question::Application.routes.draw do
  resources :my_questions

  

end

app/models/my_question.rb
class MyQuestion < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/my_questions_controller.rb
class MyQuestionsController < ApplicationController
  before_action :set_my_question, only: [:show, :edit, :update, :destroy]

  # GET /my_questions
  # GET /my_questions.json
  def index
    @my_questions = MyQuestion.all
  end

  # GET /my_questions/1
  # GET /my_questions/1.json
  def show
  end

  # GET /my_questions/new
  def new
    @my_question = MyQuestion.new
  end

  # GET /my_questions/1/edit
  def edit
  end

  # POST /my_questions
  # POST /my_questions.json
  def create
    @my_question = MyQuestion.new(my_question_params)

    respond_to do |format|
      if @my_question.save
        format.html { redirect_to @my_question, notice: 'My question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @my_question }
      else
        format.html { render action: 'new' }
        format.json { render json: @my_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_questions/1
  # PATCH/PUT /my_questions/1.json
  def update
    respond_to do |format|
      if @my_question.update(my_question_params)
        format.html { redirect_to @my_question, notice: 'My question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @my_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_questions/1
  # DELETE /my_questions/1.json
  def destroy
    @my_question.destroy
    respond_to do |format|
      format.html { redirect_to my_questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_question
      @my_question = MyQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_question_params
      params.require(:my_question).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_questions_helper.rb
module MyQuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Question</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/my_questions/_form.html.erb
<%= form_for(@my_question) do |f| %>
  <% if @my_question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_question.errors.count, "error") %> prohibited this my_question from being saved:</h2>

      <ul>
      <% @my_question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_questions/edit.html.erb
<h1>Editing my_question</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_question %> |
<%= link_to 'Back', my_questions_path %>

app/views/my_questions/index.html.erb
<h1>Listing my_questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @my_questions.each do |my_question| %>
      <tr>
        <td><%= my_question.question %></td>
        <td><%= my_question.answer %></td>
        <td><%= link_to 'Show', my_question %></td>
        <td><%= link_to 'Edit', edit_my_question_path(my_question) %></td>
        <td><%= link_to 'Destroy', my_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My question', new_my_question_path %>

app/views/my_questions/new.html.erb
<h1>New my_question</h1>

<%= render 'form' %>

<%= link_to 'Back', my_questions_path %>

app/views/my_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @my_question.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @my_question.answer %>
</p>

<%= link_to 'Edit', edit_my_question_path(@my_question) %> |
<%= link_to 'Back', my_questions_path %>